/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

/**
 * Huidige bevragingen API
 * Deze API levert actuele gegevens over adressen, adresseerbare objecten en panden. Actueel betekent in deze API `zonder eindstatus`. De bron voor deze API is de basisregistratie adressen en gebouwen (BAG).
 * <p>
 * The version of the OpenAPI document: 1.5.0
 * Contact: bag@kadaster.nl
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.bag;

import java.math.BigDecimal;
import java.time.temporal.ChronoUnit;
import java.util.List;

import javax.ws.rs.DefaultValue;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;

import org.eclipse.microprofile.faulttolerance.Timeout;
import org.eclipse.microprofile.rest.client.annotation.RegisterClientHeaders;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.annotation.RegisterProviders;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import net.atos.client.bag.model.AdresseerbaarObjectHal;
import net.atos.client.bag.model.AdresseerbaarobjectHalCollectie;
import net.atos.client.bag.model.CrsEnum;
import net.atos.client.bag.model.GebruiksdoelEnum;
import net.atos.client.bag.model.OppervlakteFilter;
import net.atos.client.bag.model.TypeAdresseerbaarObjectEnum;
import net.atos.client.bag.util.BAGClientHeadersFactory;
import net.atos.client.brp.exception.RuntimeExceptionMapper;

/**
 * Huidige bevragingen API
 *
 * <p>Deze API levert actuele gegevens over adressen, adresseerbare objecten en panden. Actueel betekent in deze API `zonder eindstatus`. De bron voor deze API is de basisregistratie adressen en gebouwen (BAG).
 */

@RegisterRestClient(configKey = "BAG-API-Client")
@RegisterClientHeaders(BAGClientHeadersFactory.class)
@RegisterProviders({
        @RegisterProvider(RuntimeExceptionMapper.class),
})
@Produces({"application/hal+json", "application/problem+json"})
@Timeout(unit = ChronoUnit.SECONDS, value = 5)
@Path("/adresseerbareobjecten")
public interface AdresseerbaarObjectApiClient {

    /**
     * levert een verblijfsobject, standplaats of ligplaats
     * <p>
     * Raadpleeg een actueel adresseerbaar object met de identificatie. Dit is de identificatie van een verblijfsobject, ligplaats of standplaats. Gebruik de fields-parameter als je alleen specifieke velden in het antwoord wil zien, zie [functionele specificaties fields-parameter](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/fields.feature). Gebruik de expand-parameter als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources adres en pand, zie [functionele specificaties expand-parameter](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/expand.feature).
     */
    @GET
    @Path("/{adresseerbaarobjectidentificatie}")
    AdresseerbaarObjectHal raadpleegAdresseerbaarobject(@PathParam("adresseerbaarobjectidentificatie") String adresseerbaarobjectidentificatie,
            @QueryParam("expand") String expand, @QueryParam("fields") String fields,
            @HeaderParam("Accept-Crs") CrsEnum acceptCrs);

    /**
     * vindt verblijfsobjecten, ligplaatsen, standplaatsen
     * <p>
     * Zoek actuele adresseerbare objecten (verblijfsobjecten, standplaatsen of ligplaatsen) met: 1. een nummeraanduidingidentificatie of 2. een pandidentificatie of 3. een lijst met pandidentificaties of 4. een geometrische contour (rechthoek) in combinatie met status geconstateerd, oppervlakte, gebruiksdoel en/of type.  Het zoeken van adresseerbare objecten met een oppervlakte en een type&#x3D;ligplaats of type&#x3D;standplaats wordt niet ondersteund en levert een foutmelding. Gebruik de fields-parameter als je alleen specifieke velden in het antwoord wil zien, zie [functionele specificaties fields-parameter](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/fields.feature). Gebruik de expand-parameter als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources adres en pand, zie  [functionele specificaties expand-parameter](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/expand.feature). Je kunt panden niet expanden als je tegelijkertijd de query parameter pandIdentificatie(s) gebruikt.
     */
    @GET
    AdresseerbaarobjectHalCollectie raadpleegAdresseerbareobjecten(@QueryParam("nummeraanduidingIdentificatie") String nummeraanduidingIdentificatie,
            @QueryParam("pandIdentificatie") String pandIdentificatie, @QueryParam("expand") String expand, @QueryParam("fields") String fields,
            @HeaderParam("Accept-Crs") CrsEnum acceptCrs, @QueryParam("page") @DefaultValue("1") Integer page,
            @QueryParam("pageSize") @DefaultValue("20") Integer pageSize, @QueryParam("pandIdentificaties") List<String> pandIdentificaties,
            @QueryParam("geconstateerd") Boolean geconstateerd, @QueryParam("type") TypeAdresseerbaarObjectEnum type,
            @QueryParam("gebruiksdoelen") List<GebruiksdoelEnum> gebruiksdoelen, @QueryParam("bbox") List<BigDecimal> bbox,
            @QueryParam("oppervlakte") OppervlakteFilter oppervlakte, @HeaderParam("Content-Crs") CrsEnum contentCrs);
}
