/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum DashboardCardType {
    MIJNDOCUMENTENNIEUW = 'MIJNDOCUMENTENNIEUW',
    MIJNTAKEN = 'MIJNTAKEN',
    MIJNTAKENNIEUW = 'MIJNTAKENNIEUW',
    MIJNZAKEN = 'MIJNZAKEN',
    MIJNZAKENNIEUW = 'MIJNZAKENNIEUW',
    MIJNZAKENWAARSCHUWING = 'MIJNZAKENWAARSCHUWING'
}
