/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum ObjectType {
    INFORMATIEOBJECT = 'INFORMATIEOBJECT',
    TAAK = 'TAAK',
    TAAKZOEKRESULTAAT = 'TAAKZOEKRESULTAAT',
    ZAAK = 'ZAAK',
    ZAAKWAARSCHUWING = 'ZAAKWAARSCHUWING',
    ZAAKZOEKRESULTAAT = 'ZAAKZOEKRESULTAAT'
}
