/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

/**
 * API Basisprofiel
 * Documentatie voor API Basisprofiel.
 * <p>
 * The version of the OpenAPI document: 1.3
 * <p>
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.kvk;

import javax.ws.rs.DefaultValue;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;

import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.annotation.RegisterProviders;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import net.atos.client.kvk.basisprofiel.model.Basisprofiel;
import net.atos.client.kvk.basisprofiel.model.Eigenaar;
import net.atos.client.kvk.basisprofiel.model.Vestiging;
import net.atos.client.kvk.basisprofiel.model.VestigingList;
import net.atos.client.kvk.exception.RuntimeExceptionMapper;

/**
 * API Basisprofiel
 *
 * <p>Documentatie voor API Basisprofiel.
 */

@RegisterRestClient(configKey = "KVK-API-Client")
@RegisterProviders({
        @RegisterProvider(RuntimeExceptionMapper.class)
})
@Produces({"application/hal+json"})
@Path("api/v1/basisprofielen/{kvkNummer}")
public interface BasisprofielClient {

    /**
     * Voor een specifiek bedrijf basisinformatie opvragen.
     */
    @GET
    Basisprofiel getBasisprofielByKvkNummer(@PathParam("kvkNummer") String kvkNummer, @QueryParam("geoData") @DefaultValue("false") Boolean geoData);

    /**
     * Voor een specifiek bedrijf eigenaar informatie opvragen.
     */
    @GET
    @Path("/eigenaar")
    Eigenaar getEigenaar(@PathParam("kvkNummer") String kvkNummer, @QueryParam("geoData") @DefaultValue("false") Boolean geoData);

    /**
     * Voor een specifiek bedrijf hoofdvestigingsinformatie opvragen.
     */
    @GET
    @Path("/hoofdvestiging")
    Vestiging getHoofdvestiging(@PathParam("kvkNummer") String kvkNummer, @QueryParam("geoData") @DefaultValue("false") Boolean geoData);

    /**
     * Voor een specifiek bedrijf een lijst met vestigingen opvragen.
     */
    @GET
    @Path("/vestigingen")
    VestigingList getVestigingen(@PathParam("kvkNummer") String kvkNummer);
}
