/*
 * SPDX-FileCopyrightText: 2021 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum ObjectType {
    ENKELVOUDIG_INFORMATIEOBJECT = 'ENKELVOUDIG_INFORMATIEOBJECT',
    TAAK = 'TAAK',
    ZAAK = 'ZAAK',
    ZAAK_INFORMATIEOBJECTEN = 'ZAAK_INFORMATIEOBJECTEN',
    ZAAK_TAKEN = 'ZAAK_TAKEN',
    ZAAK_ROLLEN = 'ZAAK_ROLLEN'
}
