/*
 * SPDX-FileCopyrightText: 2021 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

/**
 * Maps to ScreenObjectTypeEnum.java
 */
export enum ObjectType {
  BESLUIT = "BESLUIT",
  BESLUIT_INFORMATIEOBJECTEN = "BESLUIT_INFORMATIEOBJECTEN",
  ENKELVOUDIG_INFORMATIEOBJECT = "ENKELVOUDIG_INFORMATIEOBJECT",
  SIGNALERINGEN = "SIGNALERINGEN",
  TAAK = "TAAK",
  ZAAK = "ZAAK",
  ZAAK_BESLUITEN = "ZAAK_BESLUITEN",
  ZAAK_ROLLEN = "ZAAK_ROLLEN",
  ZAAK_TAKEN = "ZAAK_TAKEN",
  ZAAK_INFORMATIEOBJECTEN = "ZAAK_INFORMATIEOBJECTEN",
  ANY = "ANY",
}
