export enum ZoekenColumn {
    BEHANDELAAR = 'behandelaar',
    CREATIEDATUM = 'creatiedatum',
    DAGEN_TOT_FATALEDATUM = 'dagenTotFataledatum',
    DAGEN_TOT_STREEFDATUM = 'dagenTotStreefdatum',
    EINDDATUM = 'einddatum',
    EINDDATUM_GEPLAND = 'einddatumGepland',
    GROEP = 'groep',
    INDICATIES = 'indicaties',
    NAAM = 'naam',
    OMSCHRIJVING = 'omschrijving',
    OPENSTAANDE_TAKEN = 'openstaandeTaken',
    RESULTAAT = 'resultaat',
    SELECT = 'select',
    STARTDATUM = 'startdatum',
    STATUS = 'status',
    FATALEDATUM = 'fataledatum',
    TOELICHTING = 'toelichting',
    UITERLIJKE_EINDDATUM_AFDOENING = 'uiterlijkeEinddatumAfdoening',
    URL = 'url',
    ZAAK_DOT_IDENTIFICATIE = 'zaak.identificatie',
    ZAAK_IDENTIFICATIE = 'zaakIdentificatie',
    ZAAK_OMSCHRIJVING = 'zaakOmschrijving',
    ZAAK_TOELICHTING = 'zaakToelichting',
    ZAAKTYPE = 'zaaktype',
    ZAAKTYPE_OMSCHRIJVING = 'zaaktypeOmschrijving'
}
