/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum SignaleringType {
  ZAAK_DOCUMENT_TOEGEVOEGD = "ZAAK_DOCUMENT_TOEGEVOEGD",
  ZAAK_OP_NAAM = "ZAAK_OP_NAAM",
  TAAK_OP_NAAM = "TAAK_OP_NAAM",
  ZAAK_VERLOPEND = "ZAAK_VERLOPEND",
  TAAK_VERLOPEN = "TAAK_VERLOPEN",
}
