/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum MailtemplateEnum {
    'ZAAK_ONTVANKELIJK' = 'ZAAK_ONTVANKELIJK',
    'ZAAK_NIET_ONTVANKELIJK' = 'ZAAK_NIET_ONTVANKELIJK',
    'ZAAK_AFGEHANDELD' = 'ZAAK_AFGEHANDELD',
    'PROCES_AANVULLENDE_INFORMATIE' = 'PROCES_AANVULLENDE_INFORMATIE',
    'PROCES_ONTVANGSTBEVESTIGING' = 'PROCES_ONTVANGSTBEVESTIGING',
    'SIGNALERING_ZAAK_DOCUMENT_TOEGEVOEGD' = 'SIGNALERING_ZAAK_DOCUMENT_TOEGEVOEGD',
    'SIGNALERING_ZAAK_OP_NAAM' = 'SIGNALERING_ZAAK_OP_NAAM',
    'SIGNALERING_ZAAK_VERLOPEND_STREEFDATUM' = 'SIGNALERING_ZAAK_VERLOPEND_STREEFDATUM',
    'SIGNALERING_ZAAK_VERLOPEND_FATALE_DATUM' = 'SIGNALERING_ZAAK_VERLOPEND_FATALE_DATUM',
    'SIGNALERING_TAAK_OP_NAAM' = 'SIGNALERING_TAAK_OP_NAAM',
    'SIGNALERING_TAAK_VERLOPEN' = 'SIGNALERING_TAAK_VERLOPEN'
}
