/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum Mail {
    'ZAAK_ONTVANKELIJK' = 'ZAAK_ONTVANKELIJK',
    'ZAAK_NIET_ONTVANKELIJK' = 'ZAAK_NIET_ONTVANKELIJK',
    'ZAAK_AFGEHANDELD' = 'ZAAK_AFGEHANDELD',
    'PROCES_AANVULLENDE_INFORMATIE' = 'PROCES_AANVULLENDE_INFORMATIE',
    'PROCES_ONTVANGSTBEVESTIGING' = 'PROCES_ONTVANGSTBEVESTIGING',
    'PROCES_ADVIES' = 'PROCES_ADVIES'
}
