/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum Werklijst {
  WERKVOORRAAD_ZAKEN = "WERKVOORRAAD_ZAKEN",
  WERKVOORRAAD_TAKEN = "WERKVOORRAAD_TAKEN",
  MIJN_ZAKEN = "MIJN_ZAKEN",
  MIJN_TAKEN = "MIJN_TAKEN",
  AFGEHANDELDE_ZAKEN = "AFGEHANDELDE_ZAKEN",
  INBOX_DOCUMENTEN = "INBOX_DOCUMENTEN",
  ONTKOPPELDE_DOCUMENTEN = "ONTKOPPELDE_DOCUMENTEN",
  INBOX_PRODUCTAANVRAGEN = "INBOX_PRODUCTAANVRAGEN",
}
