/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum DatumVeld {
    STARTDATUM = 'STARTDATUM',
    STREEFDATUM = 'STREEFDATUM',
    ZAAK_EINDDATUM = 'ZAAK_EINDDATUM',
    ZAAK_UITERLIJKE_EINDDATUM_AFDOENING = 'ZAAK_UITERLIJKE_EINDDATUM_AFDOENING',
    ZAAK_REGISTRATIEDATUM = 'ZAAK_REGISTRATIEDATUM',
    ZAAK_PUBLICATIEDATUM = 'ZAAK_PUBLICATIEDATUM',
    ZAAK_STATUS_DATUM_GEZET = 'ZAAK_STATUS_DATUM_GEZET',
    TAAK_TOEKENNINGSDATUM = 'TAAK_TOEKENNINGSDATUM',
    INFORMATIEOBJECT_CREATIEDATUM = 'INFORMATIEOBJECT_CREATIEDATUM',
    INFORMATIEOBJECT_ONTVANGSTDATUM = 'INFORMATIEOBJECT_ONTVANGSTDATUM',
    INFORMATIEOBJECT_VERZENDDATUM = 'INFORMATIEOBJECT_VERZENDDATUM'
}
