/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum DatumVeld {
  STARTDATUM = "STARTDATUM",

  ZAAK_STARTDATUM = "ZAAK_STARTDATUM",
  ZAAK_EINDDATUM = "ZAAK_EINDDATUM",
  ZAAK_STREEFDATUM = "ZAAK_STREEFDATUM",
  ZAAK_FATALE_DATUM = "ZAAK_FATALE_DATUM",
  ZAAK_REGISTRATIEDATUM = "ZAAK_REGISTRATIEDATUM",
  ZAAK_PUBLICATIEDATUM = "ZAAK_PUBLICATIEDATUM",
  ZAAK_STATUS_DATUM_GEZET = "ZAAK_STATUS_DATUM_GEZET",

  TAAK_CREATIEDATUM = "TAAK_CREATIEDATUM",
  TAAK_TOEKENNINGSDATUM = "TAAK_TOEKENNINGSDATUM",
  TAAK_FATALEDATUM = "TAAK_FATALEDATUM",
  ZAAK_ARCHIEF_ACTIEDATUM = "ZAAK_ARCHIEF_ACTIEDATUM",

  INFORMATIEOBJECT_CREATIEDATUM = "INFORMATIEOBJECT_CREATIEDATUM",
  INFORMATIEOBJECT_REGISTRATIEDATUM = "INFORMATIEOBJECT_REGISTRATIEDATUM",
  INFORMATIEOBJECT_ONTVANGSTDATUM = "INFORMATIEOBJECT_ONTVANGSTDATUM",
  INFORMATIEOBJECT_VERZENDDATUM = "INFORMATIEOBJECT_VERZENDDATUM",
}
