/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum FilterVeld {
  TYPE = "TYPE",
  ZAAKTYPE = "ZAAKTYPE",
  BEHANDELAAR = "BEHANDELAAR",
  GROEP = "GROEP",
  TOEGEKEND = "TOEGEKEND",

  ZAAK_STATUS = "ZAAK_STATUS",
  ZAAK_ZAAKTYPE = "ZAAK_ZAAKTYPE",
  ZAAK_ZAAKTYPE_UUID = "ZAAK_ZAAKTYPE_UUID",
  ZAAK_BEHANDELAAR = "ZAAK_BEHANDELAAR",
  ZAAK_GROEP = "ZAAK_GROEP",
  ZAAK_RESULTAAT = "ZAAK_RESULTAAT",
  ZAAK_INDICATIES = "ZAAK_INDICATIES",
  ZAAK_COMMUNICATIEKANAAL = "ZAAK_COMMUNICATIEKANAAL",
  ZAAK_VERTROUWELIJKHEIDAANDUIDING = "ZAAK_VERTROUWELIJKHEIDAANDUIDING",
  ZAAK_ARCHIEF_NOMINATIE = "ZAAK_ARCHIEF_NOMINATIE",

  TAAK_NAAM = "TAAK_NAAM",
  TAAK_STATUS = "TAAK_STATUS",
  TAAK_ZAAKTYPE = "TAAK_ZAAKTYPE",
  TAAK_BEHANDELAAR = "TAAK_BEHANDELAAR",
  TAAK_GROEP = "TAAK_GROEP",

  DOCUMENT_STATUS = "DOCUMENT_STATUS",
  DOCUMENT_TYPE = "DOCUMENT_TYPE",
  DOCUMENT_VERGRENDELD_DOOR = "DOCUMENT_VERGRENDELD_DOOR",
  DOCUMENT_INDICATIES = "DOCUMENT_INDICATIES",
}
