/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum FilterVeld {
    ZAAKTYPE = 'ZAAKTYPE',
    BEHANDELAAR = 'BEHANDELAAR',
    GROEP = 'GROEP',
    ZAAK_STATUS = 'ZAAK_STATUS',
    ZAAK_ZAAKTYPE_UUID = 'ZAAK_ZAAKTYPE_UUID',
    ZAAK_RESULTAAT = 'ZAAK_RESULTAAT',
    TAAK_NAAM = 'TAAK_NAAM',
    TAAK_STATUS = 'TAAK_STATUS',
}
