/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum SorteerVeld {
    CREATED = 'CREATED',
    ZAAK_IDENTIFICATIE = 'ZAAK_IDENTIFICATIE',
    ZAAK_ZAAKTYPE = 'ZAAK_ZAAKTYPE',
    ZAAK_BEHANDELAAR = 'ZAAK_BEHANDELAAR',
    ZAAK_GROEP = 'ZAAK_GROEP',
    ZAAK_REGISTRATIEDATUM = 'ZAAK_REGISTRATIEDATUM',
    ZAAK_STARTDATUM = 'ZAAK_STARTDATUM',
    ZAAK_EINDDATUM_GEPLAND = 'ZAAK_EINDDATUM_GEPLAND',
    ZAAK_EINDDATUM = 'ZAAK_EINDDATUM',
    ZAAK_UITERLIJKE_EINDDATUM_AFDOENING = 'ZAAK_UITERLIJKE_EINDDATUM_AFDOENING',
    ZAAK_COMMUNICATIEKANAAL = 'ZAAK_COMMUNICATIEKANAAL',
    ZAAK_STATUS = 'ZAAK_STATUS',
    ZAAK_RESULTAAT = 'ZAAK_RESULTAAT',
    ZAAK_AANTAL_OPENSTAANDE_TAKEN = 'ZAAK_AANTAL_OPENSTAANDE_TAKEN',
    ZAAK_OMSCHRIJVING = 'ZAAK_OMSCHRIJVING',
    ZAAK_TOELICHTING = 'ZAAK_TOELICHTING',

    TAAK_NAAM = 'TAAK_NAAM',
    TAAK_STATUS = 'TAAK_STATUS',
    TAAK_ZAAK_ID = 'TAAK_ZAAK_ID',
    TAAK_ZAAKTYPE = 'TAAK_ZAAKTYPE',
    TAAK_BEHANDELAAR = 'TAAK_BEHANDELAAR',
    TAAK_GROEP = 'TAAK_GROEP',
    TAAK_CREATIEDATUM = 'TAAK_CREATIEDATUM',
    TAAK_TOEKENNINGSDATUM = 'TAAK_TOEKENNINGSDATUM',
    TAAK_STREEFDATUM = 'TAAK_STREEFDATUM',

    INFORMATIEOBJECT_TITEL = 'INFORMATIEOBJECT_TITEL',
    INFORMATIEOBJECT_ZAAK_IDENTIFICATIE = 'INFORMATIEOBJECT_ZAAK_IDENTIFICATIE',
    INFORMATIEOBJECT_CREATIEDATUM = 'INFORMATIEOBJECT_CREATIEDATUM',
    INFORMATIEOBJECT_AUTEUR = 'INFORMATIEOBJECT_AUTEUR',
    INFORMATIEOBJECT_STATUS = 'INFORMATIEOBJECT_STATUS',
    INFORMATIEOBJECT_REGISTRATIEDATUM = 'INFORMATIEOBJECT_REGISTRATIEDATUM',
    INFORMATIEOBJECT_DOCUMENTTYPE = 'INFORMATIEOBJECT_DOCUMENTTYPE',
    INFORMATIEOBJECT_ONTVANGSTDATUM = 'INFORMATIEOBJECT_ONTVANGSTDATUM',
    INFORMATIEOBJECT_VEZENDDATUM = 'INFORMATIEOBJECT_VEZENDDATUM',
}
