/*
 * SPDX-FileCopyrightText: 2021 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum ZoekVeld {
    ALLE = 'ALLE',

    ZAAK_IDENTIFICATIE = 'ZAAK_IDENTIFICATIE',
    ZAAK_OMSCHRIJVING = 'ZAAK_OMSCHRIJVING',
    ZAAK_TOELICHTING = 'ZAAK_TOELICHTING',
    ZAAK_INITIATOR = 'ZAAK_INITIATOR',

    TAAK_ZAAK_ID = 'TAAK_ZAAK_ID',
    TAAK_TOELICHTING = 'TAAK_TOELICHTING',

    DOCUMENT_TITEL = 'DOCUMENT_TITEL',
    DOCUMENT_BESCHRIJVING = 'DOCUMENT_BESCHRIJVING',

}
