/*
 * SPDX-FileCopyrightText: 2021 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum FieldType {
  AUTOCOMPLETE = "AUTOCOMPLETE",
  INPUT = "INPUT",
  FILE = "FILE",
  HEADING = "HEADING",
  HIDDEN = "HIDDEN",
  HTML_EDITOR = "HTML_EDITOR",
  PARAGRAPH = "PARAGRAPH",
  TEXTAREA = "TEXTAREA",
  DATE = "DATE",
  DIVIDER = "DIVIDER",
  SELECT = "SELECT",
  MEDEWERKER_GROEP = "MEDEWERKER_GROEP",
  RADIO = "RADIO",
  DOCUMENTEN_LIJST = "DOCUMENTEN_LIJST",
  DOCUMENTEN_ONDERTEKENEN = "DOCUMENTEN_ONDERTEKENEN",
  CHECKBOX = "CHECKBOX",
  GOOGLEMAPS = "GOOGLEMAPS",
  READONLY = "READONLY",
  TAAK_DOCUMENT_UPLOAD = "TAAK_DOCUMENT_UPLOAD",
  MESSAGE = "MESSAGE",
}
