###
# Create Melding object
POST http://objects.object-registratie/objects/api/v1/objects
Authorization: {{objectsApiToken}}
Content-Type: application/json
Content-Crs: EPSG:4326

{
  "record": {
    "data": {
      "categorie": "Hoofd 1",
      "melder": {
        "e-mailadres": "a@b.c"
      },
      "toelichting": "Test"
    },
    "startAt": "2021-01-31",
    "typeVersion": 3
  },
  "type": "http://objecttypes.object-registratie/objecttypes/api/v1/objecttypes/d7775e82-9c47-4093-82a9-3dcc0d1c8a42"
}
> {%
client.global.set("objectURI", response.headers.valueOf("Location"));
%}

###
# Create Zaak
POST http://open-zaak.open-zaak/zaken/api/v1/zaken
Content-Type: application/json
Authorization: {{jwt}}
Accept-Crs: EPSG:4326
Content-Crs: EPSG:4326

{
  "bronorganisatie": "622439224",
  "startdatum": "2021-01-31",
  "verantwoordelijkeOrganisatie": "130433226",
  "zaaktype": "http://open-zaak.open-zaak/catalogi/api/v1/zaaktypen/418ef5a1-efbc-4564-9c2f-e9389c95d644"
}
> {%
client.global.set("zaakURI", response.headers.valueOf("Location"));
 %}

###
# Create Zaakobject
POST http://open-zaak.open-zaak/zaken/api/v1/zaakobjecten
Content-Type: application/json
Authorization: {{jwt}}

{
  "object": "{{objectURI}}",
  "objectType": "overige",
  "objectTypeOverige": "Melding Openbare Ruimte",
  "relatieomschrijving": "mor_melding",
  "zaak": "{{zaakURI}}"
}

###
# Notificeer nieuwe zaak
POST {{zaakafhandelcomponentHost}}/zac/rest/notificaties
Content-Type: application/json

{
  "kanaal" : "zaken",
  "hoofdObject" : "{{zaakURI}}",
  "resource" : "zaak",
  "resourceUrl" : "{{zaakURI}}",
  "actie" : "create",
  "aanmaakdatum" : "2021-05-05T10:31:36.456698Z"
}
