/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum BAGObjecttype {
  ADRES = "ADRES",
  ADRESSEERBAAR_OBJECT = "ADRESSEERBAAR_OBJECT",
  WOONPLAATS = "WOONPLAATS",
  PAND = "PAND",
  OPENBARE_RUIMTE = "OPENBARE_RUIMTE",
  NUMMERAANDUIDING = "NUMMERAANDUIDING",
}
