export enum SideNavAction {
    GEEN = 'GEEN',
    ZOEK_INITIATOR = 'ZOEK_INITIATOR',
    ZOEK_BETROKKENE = 'ZOEK_BETROKKENE',
    ZOEK_LOCATIE = 'ZOEK_LOCATIE',
    DOCUMENT_MAKEN = 'DOCUMENT_MAKEN',
    DOCUMENT_TOEVOEGEN = 'DOCUMENT_TOEVOEGEN',
    DOCUMENT_VERSIE_TOEVOEGEN = 'DOCUMENT_VERSIE_TOEVOEGEN',
    MAIL_VERSTUREN = 'MAIL_VERSTUREN',
    TAAK_STARTEN = 'TAAK_STARTEN',
    ONTVANGSTBEVESTIGING = 'ONTVANGSTBEVESTIGING',
    ZOEK_BAG_OBJECT = 'ZOEK_BAG_OBJECT'
}
