export enum SideNavAction {
    GEEN = 'GEEN',
    ZOEK_PERSOON = 'ZOEK_PERSOON',
    ZOEK_BEDRIJF = 'ZOEK_BEDRIJF',
    ZOEK_LOCATIE = 'ZOEK_LOCATIE',
    DOCUMENT_TOEVOEGEN = 'DOCUMENT_TOEVOEGEN',
    DOCUMENT_VERSIE_TOEVOEGEN = 'DOCUMENT_VERSIE_TOEVOEGEN',
    MAIL_VERSTUREN = 'MAIL_VERSTUREN',
    TAAK_STARTEN = 'TAAK_STARTEN',
    ONTVANGSTBEVESTIGING = 'ONTVANGSTBEVESTIGING'
}
