/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum AardVanRol {
  ADVISEUR = "ADVISEUR",
  BEHANDELAAR = "BEHANDELAAR",
  BELANGHEBBENDE = "BELANGHEBBENDE",
  BESLISSER = "BESLISSER",
  INITIATOR = "INITIATOR",
  KLANTCONTACTER = "KLANTCONTACTER",
  ZAAKCOORDINATOR = "ZAAKCOORDINATOR",
  MEDE_INITIATOR = "MEDE_INITIATOR",
}
